// Generated by generate.mjs: this package's API on each marketplace.
export const API_TITLE = 'Website Contact Extractor for Emails and Phones';
export const API_MARKET_SLUG = 'contact-extractor';
export const RAPIDAPI_HOST = 'website-contact-extractor-for-emails-and-phones.p.rapidapi.com';
